FROM python:3.10-bullseye

# Upgrade System and Install dependencies
RUN apt-get update && \
  apt-get upgrade -y -o DPkg::Options::=--force-confold && \
  apt-get install -y -o DPkg::Options::=--force-confold curl netcat

# Install Latest Salt from the stable Branch
RUN curl -o bootstrap-salt.sh -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh && \
    sh bootstrap-salt.sh -X -D -P stable && \
    rm bootstrap-salt.sh

# Set master
COPY saltconfig/etc/minion /etc/salt/minion

COPY utils/entrypoint-minion.sh .

ENTRYPOINT ["./entrypoint-minion.sh"]
